name: Publish Helm charts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: jcs1910/helm-repo@main
        with:
          token: #{{ secrets.GITHUB_TOKEN }}
